services:
  db:
    image: mysql:8.0
    container_name: slp_lms_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SLP_lms
      # MYSQL_USER: testuser
      # MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend
      # dockerfile: ./backend/Dockerfile
    container_name: slp_lms_backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    # command: ["npm", "run", "start"]
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      # dockerfile: ./frontend/Dockerfile
    container_name: slp_lms_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:3001

volumes:
  db_data:
